---
title: "DAGs propuestas"
format: html
editor: visual
---

## DAGs propuestas por especialistas
```{r}
#install.packages("tidyverse")
#install.packages("bnlearn")
```

```{r}
library(tidyverse)
library(bnlearn)
```

```{r}
#data = read_csv("base de datos limpia")
#head(data)
```

```{r}
#data = data |> #pipeline
        #select(-crop)#todo menos crop
```

```{r}
#head(data)
```

```{r}
#colnames(data) = c("N", "P", "K", "T", "H", "pH", "R", "Y") #cambiamos el nombre de las columnas, en caso de ser necesario, si no las mismas variables permanecen
```


DAG 1:
Propuesta por el nutriólogo y especialista en ciencias médicas Alberto Bricio.

```{r}
dag1 = model2network("[h0302][h0303][region][CO][SO2][valor_HCST][valor_INSULINA][estrato|municipio][municipio|entidad][entidad|region][valor_PCR|valor_HCST:SO2][valor_VIT_B12|valor_HCST:estrato][valor_GLU_SUERO|valor_PCR][valor_COLEST|valor_PCR][valor_VIT_D|h0303][valor_HB1AC|valor_INSULINA][valor_ALBU|CO][PM10|estrato][hb02|estrato:h0302]") 
```

```{r}
dag1
```

```{r}
library(Rgraphviz)
graphviz.plot(dag1, shape = "ellipse")
```

